P507/19. 11.06.2020/11062020/Models/Service.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace _11062020.Models
{
    public class Service
    {
        public int Id { get; set; }

        [Required, StringLength(200)]
        public string Title { get; set; }

        [Required, MinLength(100)]
        public string Description { get; set; }

        public List<ServicePhoto> ServicePhotos { get; set; }
    }
}

P507/19. 11.06.2020/11062020/Models/ServicePhoto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _11062020.Models
{
    public class ServicePhoto
    {
        public int Id { get; set; }

        [Required, StringLength(100)]
        public string Path { get; set; }

        public int ServiceId { get; set; }

        public Service Service { get; set; }
    }
}

P507/19. 11.06.2020/11062020/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using _11062020.DAL;
using _11062020.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _11062020.Controllers
{
    public class HomeController : Controller
    {
        private readonly LabDbContext _db;
        public HomeController(LabDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Service> services = _db.Services.Include(s=>s.ServicePhotos).ToList();

            return View(services);
        }
    }
}

P507/19. 11.06.2020/11062020/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _11062020.DAL;
using _11062020.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _11062020.Controllers
{
    public class ServiceController : Controller
    {
        private readonly LabDbContext _db;

        public ServiceController(LabDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Service> services = _db.Services.Include(s => s.ServicePhotos).ToList();

            return View(services);
        }

        public IActionResult Details(int id)
        {
            Service service = _db.Services.Include(s => s.ServicePhotos).FirstOrDefault(s => s.Id == id);

            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }
    }
}

P507/19. 11.06.2020/11062020/Views/Service/Details.cshtml
@model Service
@{
    ViewData["Title"] = "Details";
}

<!-- breadcrumb-banner-area -->
<div class="breadcrumb-banner-area ptb-120 bg-opacity" style="background-image:url(assets/img/bg/6.jpg)">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text text-center">
                    <h2>service-details</h2>
                    <ul class="breadcrumb-menu">
                        <li><a href="~/#">service</a></li>
                        <li><a href="~/#">about us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb-banner-area-end -->
<!-- project-details-area-start -->
<div class="project-details-area pt-120">
    <div class="container">
        <div class="row">
            @foreach (ServicePhoto servicePhoto in Model.ServicePhotos)
            {
                <div class="col-md-6 col-sm-6">
                    <div class="project-details-img-wrapper">
                        <img src="~/assets/img/service/@servicePhoto.Path" alt="@Model.Title" />
                    </div>
                </div>
            }

        </div>
    </div>
</div>
<!-- project-details-area-start -->
<!-- project-details-3-start -->
<div class="project-details-3 pt-40 pb-50">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="project-text">
                    <h3>@Model.Title</h3>
                    <p>@Model.Description</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- project-details-3-end -->	

P507/19. 11.06.2020/11062020/Views/Service/Index.cshtml
@model List<Service>
@{
    ViewData["Title"] = "Index";
}
<!-- breadcrumb-banner-area -->
<div class="breadcrumb-banner-area ptb-120 bg-opacity" style="background-image:url(~/assets/img/bg/6.jpg)">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text text-center">
                    <h2>service</h2>
                    <ul class="breadcrumb-menu">
                        <li><a href="~/#">service</a></li>
                        <li><a href="~/#">about us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb-banner-area-end -->
<!-- our-service-area-start -->
<div class="our-service-area pt-120 pb-90">
    <div class="container">
        <div class="section-title mb-60 text-center" style="background-image:url(~/assets/img/logo/section.png)">
            <h4>We Provide</h4>
            <h2>Our Services</h2>
        </div>
        <div class="row">
            @foreach (Service service in Model)
            {
                <div class="col-md-4 col-sm-6">
                    <div class="service-wrapper mb-30">
                        <div class="service-img">
                            <img src="~/assets/img/service/@service.ServicePhotos.FirstOrDefault().Path" alt="" />
                        </div>
                        <div class="service-text text-center">
                            <div class="service-icon-img">
                                <i class="flaticon-house-icon"></i>
                            </div>
                            <h2><a href="@Url.Action("Details","Service", new { id = service.Id })">@service.Title</a></h2>
                            <p>@(service.Description.Length > 150 ? service.Description.Substring(0, 150) + "..." : service.Description)</p>
                            <a href="@Url.Action("Details","Service", new { id = service.Id })">read more</a>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>
<!-- our-service-area-end -->