Tasks for myself/MultiFileUpload/MultiFileUpload/Models/Photo.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MultiFileUpload.Models
{
    public class Photo
    {
        public int Id { get; set; }

        [Required]
        public string ImagePath { get; set; }

        [NotMapped, Required]
        public IFormFile[] Files { get; set; }
    }
}

Tasks for myself/MultiFileUpload/MultiFileUpload/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MultiFileUpload.DAL;
using MultiFileUpload.Models;

namespace MultiFileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly FileUploadContext _context;
        private readonly IHostingEnvironment _env;

        public FileUploadController(FileUploadContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(Photo photo)
        {
            if (photo.Files == null || photo.Files.Length == 0)
            {
                ModelState.AddModelError("Files","Please select at least 1 image file");
                return View();
            }

            foreach (IFormFile img in photo.Files)
            {
                if (!img.ContentType.Contains("image/"))
                {
                    ModelState.AddModelError("Files", "You don't have an access for adding different type of file!");
                    return View();
                }
                else
                {
                    var imgSave = Path.Combine(_env.WebRootPath, "img");
                    string fileName = Guid.NewGuid().ToString() + img.FileName;
                    string path = Path.Combine(imgSave, fileName);
                    FileStream stream = new FileStream(path, FileMode.Create);

                    await img.CopyToAsync(stream);

                    Photo newPhoto = new Photo { ImagePath = fileName };
                    //photo.ImagePath = fileName;

                    await _context.Photos.AddAsync(newPhoto);
                    await _context.SaveChangesAsync();
                }

            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Tasks for myself/MultiFileUpload/MultiFileUpload/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MultiFileUpload.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Tasks for myself/MultiFileUpload/MultiFileUpload/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MultiFileUpload.DAL;
using MultiFileUpload.Models;

namespace MultiFileUpload.Controllers
{
    public class PhotosController : Controller
    {
        private readonly FileUploadContext _context;

        public PhotosController(FileUploadContext context)
        {
            _context = context;
        }

        // GET: Photos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Photos.ToListAsync());
        }

        // GET: Photos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // GET: Photos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImagePath")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(photo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(photo);
        }

        // GET: Photos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.FindAsync(id);
            if (photo == null)
            {
                return NotFound();
            }
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImagePath")] Photo photo)
        {
            if (id != photo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(photo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotoExists(photo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(photo);
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var photo = await _context.Photos.FindAsync(id);
            _context.Photos.Remove(photo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhotoExists(int id)
        {
            return _context.Photos.Any(e => e.Id == id);
        }
    }
}

Tasks for myself/MultiFileUpload/MultiFileUpload/Views/FileUpload/Index.cshtml
@model Photo
@{
    ViewData["Title"] = "Index";
}
<h2>Multi File Upload Management</h2>
<hr />

<form method="post" enctype="multipart/form-data" asp-controller="FileUpload" asp-action="Index">
    <div class="form-group">
        <input asp-for="Files" type="file" name="files" class="lol" multiple />
        <input asp-for="Files" type="submit" value="Submit" />
        <span asp-validation-for="Files" class="text-danger"></span>
        <hr />
    </div>
</form>


@section Scripts{
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $(document).ready(function () {
            $("form").submit(function (e) {
                e.preventDefault();
                if (document.querySelector(".lol").value == "") {
                    swal({
                        title: "Please select at least 1 file!",
                        icon: "warning"
                    });
                } else {
                    //swal("Files uploaded !").then(() => {
                    //    document.querySelector("form").submit();
                    //});
                    swal({
                        title: "Are you sure to upload files?",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                        .then((willDelete) => {
                            if (willDelete) {
                                swal("Files Uploaded!", {
                                    icon: "success",
                                });
                                setTimeout(() => { document.querySelector("form").submit() }, 2000)
                            } else {
                                swal("You postponed!");
                            }
                        });
                }
            });
        });
    </script>
}